export type OrbProperty = "orbSpawnRate" | "orbSpawnCount"
export type HealthProperty = "maxHealthPercent" | "maxHealthFlat" | "healthRegenInterval" | "healthRegenFlat" | "healthRegenPercent" | "healthRegenCooldown"
export type DamageType = "meleeDamage" | "rangedDamage" | "magicDamage"
export type CritProperty = "critChance" | "critMulti"
export type DefenseProperty = "defenseFlatValue" | "defensePercentValue"
export type ShieldProperty = "maxShield" | "shieldRegenInterval" | "shieldRegenFlat" | "shieldRegenPercent" | "shieldRegenCooldown"
export type ManaProperty = "maxMana" | "manaRegenFlatPerOrb" | "manaRegenPercentPerOrb"

return {}